# Use the base image
FROM steamcmd/steamcmd:ubuntu-20

ENV STEAM_DIR /home/steam
ENV STEAMCMD_DIR /home/steam/steamcmd
ENV APP_ID 730
ENV APP_DIR /home/steam/cs2

# Create the directory in the container
RUN mkdir -p $APP_DIR

# Specify the volume
VOLUME $APP_DIR

# CMD ["sh", "-c", "sleep", "60000"]  #debug

ENTRYPOINT []

# Default command, for example, you can run steamcmd. Adjust as necessary.
CMD ["./steamcmd.sh"]

